name: Lint and Flake

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0
      - name: python-flake8
        uses: julianwachholz/flake8-action@v2.0.2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


